export const seriesMapPalette = {
    "Super Mario": 'red',
    "Donkey Kong": 'orange',
    "The Legend of Zelda": 'green',
    "Breath of the Wild": 'green',
    "Animal Crossing": 'yellow',
    "Metroid": 'blue',
    "Wii Fit": 'blue',
    "Classic Nintendo": 'grey',
    "Splatoon": 'orange',
    "Pokemon": 'red',
    "Kirby": 'pink',
    "Fire Emblem": 'blue',
    'Xenoblade': 'red',
    "Sonic": 'blue',
    "Bayonetta": 'pink',
    "Pac-man": 'yellow',
    "Megaman": 'blue',
    "Final Fantasy": 'grey',
    "Castlevania": 'blue',
    "Persona": 'grey',
    "Banjo Kazooie": 'orange',
    "Minecraft": 'green',
};
