export const colors = [
    'pink',
    'red',
    'orange',
    'yellow',
    'green',
    'blue',
    'purple',
    'grey',
];

export const seriesMapPalette = {
    "-- unknown --": 'grey',
    "Super Mario": 'red',
    "Donkey Kong": 'orange',
    "The Legend of Zelda": 'green',
    "Breath of the Wild": 'orange',
    "Animal Crossing": 'yellow',
    "Metroid": 'blue',
    "Wii Fit": 'blue',
    "Classic Nintendo": 'grey',
    "Splatoon": 'orange',
    "Pokemon": 'red',
    "Kirby": 'pink',
    "Fire Emblem": 'blue',
    "Xenoblade": 'grey',
    "Sonic": 'blue',
    "Shovel Knight": 'purple',
    "Street fighter": 'grey',
    "Star Fox": 'purple',
    "Bayonetta": 'blue',
    "Pac-man": 'yellow',
    "Metal Gear Solid": 'grey',
    "Megaman": 'blue',
    "Final Fantasy": 'grey',
    "Castlevania": 'purple',
    "Persona": 'grey',
    "Banjo Kazooie": 'orange',
    "Dragon Quest": 'pink',
    "Mii": 'yellow',
    "Minecraft": 'orange',
    "ARMS": 'green',
};
